"""OpenClaw subprocess boundary for the worker."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass
class OpenClawResult:
    success: bool
    markdown: str
    stderr: str = ""
    called: bool = False
    error: str = ""
    returncode: int | None = None
    prompt_file: Path | None = None


def mock_markdown() -> str:
    return """# Daily Briefing

## Calendar Summary

- Mock calendar summary generated by the worker.

## Email Requiring Attention

- Mock email follow-up for review.

## Project Notes

- Mock project note for MTA-Transit.

## Commitments Detected

- Review generated briefing before filing.

## Follow-Ups

- Confirm next source integration phase.

## Draft Replies for Review

- No outbound email is sent by this worker.

## Risks / Open Questions

- Real integrations are intentionally not connected in this skeleton.

## Suggested Obsidian Links

- [[MTA-Transit]]
"""


def run_openclaw(prompt: str, config: dict, dry_run: bool = False, mock: bool = False) -> OpenClawResult:
    if dry_run or mock:
        return OpenClawResult(
            success=True,
            markdown=mock_markdown(),
            called=False,
        )

    tmp_path = Path(config["tmp_path"])
    tmp_path.mkdir(parents=True, exist_ok=True)
    prompt_file = tmp_path / "openclaw_prompt.md"
    prompt_file.write_text(prompt, encoding="utf-8")

    command = config["openclaw_command"].format(
        skill=config["openclaw_skill"],
        prompt_file=str(prompt_file),
    )
    timeout = int(config.get("openclaw_timeout_seconds", 180))
    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
            shell=True,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return OpenClawResult(
            success=False,
            markdown="",
            stderr=str(exc),
            called=True,
            error=f"OpenClaw command failed to start or timed out: {exc}",
            prompt_file=prompt_file,
        )

    if completed.returncode != 0:
        return OpenClawResult(
            success=False,
            markdown="",
            stderr=completed.stderr,
            called=True,
            error=f"OpenClaw command exited with code {completed.returncode}",
            returncode=completed.returncode,
            prompt_file=prompt_file,
        )

    return OpenClawResult(
        success=True,
        markdown=completed.stdout,
        stderr=completed.stderr,
        called=True,
        returncode=completed.returncode,
        prompt_file=prompt_file,
    )
